### ISSUE TITLE
Research information for the site

### ISSUE THREAD

**Issue by manni8436** [manni8436/a-better-world#10]
- [x] - Ideate sections for website

**Comment by GreenGraf** [comment]
![AdobeColor-Sustainabillibuddies](https://user-images.githubusercontent.com/94128373/164511273-138e506c-a00e-4e66-bbbe-f59be5417ee2.jpeg)
![Uploading AdobeColor-My Color Blind Safe Theme.jpeg…]()

**Comment by gretazas** [comment]
https://www.bbc.com/news/science-environment-46459714
