### ISSUE TITLE
Create Array of Objects of Data for Carbon Count Page

### ISSUE THREAD

**Issue by jonathanmeaney-lmk** [manni8436/a-better-world#19]
Example 
{  product: 'beef', section: food, carbon_count: 27, equiv_one: '67 car miles driven', equiv_two: - 29.9lb of coal burned, equiv_three: '3 gallons of gasoline consumed' }

**Comment by gretazas** [comment]
[done-products-list.txt](https://github.com/manni8436/earth-day-hackathon-2022/files/8548597/done-products-list.txt)
